infrastructure:
  redis:
    hosts: "localhost:6379"
    password: ""
    db: 1
    maxRetries: 5
    readTimeout: 5s
    writeTimeout: 5s
datalayer:
  command:
    mode: "redis"
    useTransaction: true
  query:
    mode: "redis"
    useTransaction: false
controller:
  port: 8081
middleware:
  authUrl: "http://localhost:8081/auth"
  cors: true