infrastructure:
  redis:
    hosts: "localhost:6379"
    password: ""
    db: 1
    maxRetries: 5
    readTimeout: 5s
    writeTimeout: 5s
  mongo:
    hosts: "localhost:27017"
    username: "people-service"
    password: "abc123!"
    maxRetries: 5
    readTimeout: 5s
    writeTimeout: 5s
controller:
  port: 8080  
datalayer:
  command:
    mode: "mongo"
    db: "church-management"
    useTransaction: false
  query:
    db: "church-management"
    mode: "mongo"

    useTransaction: false
middleware:
  authUrl: "http://localhost:8081/auth"
  cors: true
  