// Code generated by mockery v2.34.2. DO NOT EDIT.

package mocks

import (
	repositories "github.com/Goldwin/ies-pik-cms/pkg/auth/repositories"
	mock "github.com/stretchr/testify/mock"
)

// Context is an autogenerated mock type for the Context type
type Context struct {
	mock.Mock
}

type Context_Expecter struct {
	mock *mock.Mock
}

func (_m *Context) EXPECT() *Context_Expecter {
	return &Context_Expecter{mock: &_m.Mock}
}

// AccountRepository provides a mock function with given fields:
func (_m *Context) AccountRepository() repositories.AccountRepository {
	ret := _m.Called()

	var r0 repositories.AccountRepository
	if rf, ok := ret.Get(0).(func() repositories.AccountRepository); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(repositories.AccountRepository)
		}
	}

	return r0
}

// Context_AccountRepository_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AccountRepository'
type Context_AccountRepository_Call struct {
	*mock.Call
}

// AccountRepository is a helper method to define mock.On call
func (_e *Context_Expecter) AccountRepository() *Context_AccountRepository_Call {
	return &Context_AccountRepository_Call{Call: _e.mock.On("AccountRepository")}
}

func (_c *Context_AccountRepository_Call) Run(run func()) *Context_AccountRepository_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Context_AccountRepository_Call) Return(_a0 repositories.AccountRepository) *Context_AccountRepository_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Context_AccountRepository_Call) RunAndReturn(run func() repositories.AccountRepository) *Context_AccountRepository_Call {
	_c.Call.Return(run)
	return _c
}

// OtpRepository provides a mock function with given fields:
func (_m *Context) OtpRepository() repositories.OtpRepository {
	ret := _m.Called()

	var r0 repositories.OtpRepository
	if rf, ok := ret.Get(0).(func() repositories.OtpRepository); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(repositories.OtpRepository)
		}
	}

	return r0
}

// Context_OtpRepository_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OtpRepository'
type Context_OtpRepository_Call struct {
	*mock.Call
}

// OtpRepository is a helper method to define mock.On call
func (_e *Context_Expecter) OtpRepository() *Context_OtpRepository_Call {
	return &Context_OtpRepository_Call{Call: _e.mock.On("OtpRepository")}
}

func (_c *Context_OtpRepository_Call) Run(run func()) *Context_OtpRepository_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Context_OtpRepository_Call) Return(_a0 repositories.OtpRepository) *Context_OtpRepository_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Context_OtpRepository_Call) RunAndReturn(run func() repositories.OtpRepository) *Context_OtpRepository_Call {
	_c.Call.Return(run)
	return _c
}

// NewContext creates a new instance of Context. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewContext(t interface {
	mock.TestingT
	Cleanup(func())
}) *Context {
	mock := &Context{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
